<?php

namespace cufm\SedaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluacionObreroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionObreroRepository extends EntityRepository
{
}
